// Generated by BUCKLESCRIPT VERSION 2.2.0, PLEASE EDIT WITH CARE
'use strict';


var _appId = "0a9fd7c5-856f-484a-b40b-d8d63e4f2fb3";

var appId = "0a9fd7c5-856f-484a-b40b-d8d63e4f2fb3";

exports._appId = _appId;
exports.appId = appId;
/* No side effect */
